eureka:
  instance:
    lease-renewal-interval-in-seconds: 10 #表示eureka client发送心跳给server端的频率，默认为30秒
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/