spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization:
      accept_empty_string_as_null_object: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  security:
    user:
      name: admin
      password: 123456

  cloud:
    config:
      enabled: false
      retry:
        max-attempts: 6
        multiplier: 1.1
        initial-interval: 1000
        max-interval: 2000

executor:
  corePoolSize: 3
  maxPoolSize: 50
  queueCapacity:  500


