ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000
  SocketTimeout: 15000
  MaxTotalConnections: 15000
  MaxConnectionsPerHost: 500
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0
  OkToRetryOnAllOperations: true
  # ServerListRefreshInterval: 2000
  #  eureka:
  #    enable: true
  #  eager-load:
  #    enabled: true

#  eager-load:
#    enabled: true
#    clients: ${EAGER_LOAD}